/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#191c1e",
        "primary-fixed-dim": "#b7c4ff",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-fixed": "#3c0800",
        "surface-variant": "#e0e3e5",
        "on-tertiary-container": "#ffddd5",
        "surface-container": "#eceef0",
        "on-secondary-fixed-variant": "#31476b",
        "surface-container-low": "#f2f4f6",
        "outline-variant": "#c3c5d9",
        "on-surface": "#191c1e",
        "secondary-fixed": "#d6e3ff",
        "secondary-container": "#bcd2fe",
        "secondary-fixed-dim": "#b1c7f2",
        "on-secondary-container": "#445a7f",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#891e00",
        "inverse-on-surface": "#eff1f3",
        "on-primary-container": "#dfe3ff",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001452",
        "tertiary-fixed": "#ffdbd2",
        "surface-dim": "#d8dadc",
        "tertiary-fixed-dim": "#ffb4a1",
        "inverse-primary": "#b7c4ff",
        "tertiary-container": "#bf3003",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "primary-container": "#0052ff",
        secondary: "#495f84",
        "on-primary": "#ffffff",
        "on-surface-variant": "#434656",
        primary: "#003ec7",
        "surface-container-highest": "#e0e3e5",
        surface: "#f7f9fb",
        "inverse-surface": "#2d3133",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#dde1ff",
        "on-primary-fixed-variant": "#0038b6",
        "on-secondary": "#ffffff",
        "surface-tint": "#004ced",
        background: "#f7f9fb",
        "surface-bright": "#f7f9fb",
        outline: "#737688",
        "surface-container-lowest": "#ffffff",
        tertiary: "#952200",
        "on-secondary-fixed": "#001b3d",
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
  plugins: [],
};